schema: https://api.linear.app/graphql
documents:
  - ./linear.ts
extensions:
  codegen:
    generates:
      ./types.generated.ts:
        plugins:
          - typescript
          - typescript-operations
        config:
          enumsAsTypes: true
          onlyOperationTypes: true
          useImplementingTypes: true
